kmit-radiology-main-3/covid/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'covid'

urlpatterns = [
    url(r'^$', views.CovidHome, name="covid_home"),
    url(r'^upload_covid/$', views.uploadCovid, name="upload_covid"),
    url(r'^predictCovid/$', views.predictCovid, name="predict_covid"),
    url(r'^showCovid/$', views.showCovid, name="show_covid"),
    url(r'^getCovitCT/$', views.getCovidList, name="list_covid"),
    url(r'^sent/$', views.sentImage, name="sent_Image")
    # url(r'^fileupload/$', views.uploadToServer, name="upload_server")
]

kmit-radiology-main-3/kmit/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url,include
from django.urls import path
from django.urls import re_path
from django.views.static import serve

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.Home,  name="Home"),
    path("DICOM-viewer", views.Viewer, name="Viewer"),
    path('Mammography/', include('mammo.urls')), # mammo => folder name
    path('auth/', include('auths.urls')),
    path('covid/', include('covid.urls')),
]

urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

kmit-radiology-main-3/covid/models.py
from django.db import models

# Create your models here.

kmit-radiology-main-3/covid/views.py
import requests
import warnings
from tensorflow.keras import backend as K
import keras_unet
from tensorflow import keras
import tensorflow as tf
import png
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage

# Numerics
import nibabel as nib
import cv2
import numpy as np
import random
from PIL import Image as im
import random
import io

import glob
from PIL import Image
import pydicom

# Visuals
import matplotlib.pyplot as plt
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from tqdm import tqdm
from django.template.defaulttags import register


# Env
import os
from os import path
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = ""
os.environ['TF_CPP_MIN_LOG_LEVEL'] = ''

# Backend
# import keras
warnings.filterwarnings("ignore")


@register.filter
def get_item(dictionary, key):
    return dictionary[key]


def CovidHome(request):
    userFile = request.user
    # print(userFile)
    outputdir = 'media/covidFiles/' + str(userFile) + '/'
    isDir = os.path.isdir(outputdir)
    if (isDir == False):
        os.mkdir(outputdir)
    dcm_folder = outputdir + "DCM_Folder" + "/"
    is_dcm = os.path.isdir(dcm_folder)
    if(is_dcm == False):
        os.mkdir(dcm_folder)
    predicted_folder = outputdir + "Predicted_Folder" + "/"
    is_predicted = os.path.isdir(predicted_folder)
    if(is_predicted == False):
        os.mkdir(predicted_folder)
    return render(request, 'covidct/Covid_Home.html')


@login_required(login_url='/auth/login')
def uploadCovid(request):
    userFile = request.user
    outputdir = 'media/covidFiles/' + str(userFile) + '/DCM_Folder/'
    if(request.method == 'POST'):
        imgName = request.FILES['covid_document']
        # print(imgName.name)
        fs = FileSystemStorage(location=outputdir, base_url=outputdir)
        x = fs.save(imgName.name, imgName)
        filename = Convert_To_PNG(x, userFile)
        # os.remove(outputdir + x)
        context['url'] = fs.url(filename)
        # print(context['url'])
    return render(request, 'covidct/upload_Covid.html')


def Convert_To_PNG(dcmFile, username):
    file = dcmFile
    context = {}
    userFile = username
    inputdir = 'media/covidFiles/' + str(userFile) + '/DCM_Folder/'
    outputdir = 'media/covidFiles/' + str(userFile) + '/DCM_Folder/'
    test_list = [os.path.basename(x) for x in glob.glob(inputdir + '*.dcm')]
    # print(test_list)
    for f in test_list:
        if(f == file):
            ds = pydicom.read_file(inputdir + f)
            img = ds.pixel_array
            cv2.imwrite(outputdir + f.replace('.dcm', '.png'), img)
    out_list = [os.path.basename(x) for x in glob.glob(inputdir + '*.png')]
    for name in out_list:
        if(name[:-4] == file[:-4]):
            return name


@login_required(login_url='/auth/login')
def getCovidList(request):
    userFile = request.user
    if userFile.is_superuser:
        cl = {}
        for (root, dirs, files) in os.walk('media/covidFiles'):
            for i in files:
                # dir_list.append(i)
                # dir=os.path.join(root,i)
                dir_list = os.listdir(root)
                for dimg in dir_list:
                    covidList = {}
                    tmpFile = dimg
                    if(tmpFile.endswith('.dcm')):
                        filename = root + "/" + tmpFile
                        dataset = pydicom.dcmread(filename)
                        y = dataset.data_element("PatientID").value
                        covidList["PatientID"] = y
                        x = dataset.data_element("PatientName").value
                        covidList["PatientName"] = x
                        covidList["PatientSex"] = dataset.data_element(
                            "PatientSex").value
                        covidList["PatientAge"] = dataset.data_element(
                            "PatientAge").value
                        covidList["StudyDate"] = dataset.data_element(
                            "StudyDate").value
                        covidList["Modality"] = dataset.data_element(
                            "Modality").value
                        covidList["ImageComments"] = dataset.data_element(
                            "ImageComments").value
                        covidList["SeriesDescription"] = dataset.data_element(
                            "SeriesDescription").value
                        covidList["BodyPartExamined"] = dataset.data_element(
                            "BodyPartExamined").value
                        covidList["User"] = root.split("/")[-2]
                        cl[dimg] = covidList
        return render(request, "covidct/listCovid.html", {"cl": cl})

    else:
        cl = {}
        outputdir = "media/covidFiles/" + str(userFile) + "/DCM_Folder/"
        isDir = os.path.isdir(outputdir)
        if (isDir == False):
            os.mkdir(outputdir)
        # cl = {}
        dir = outputdir
        dir_list = os.listdir(dir)
        for dimg in dir_list:
            covidList = {}
            tmpFile = dimg
            if(tmpFile.endswith('.dcm')):
                filename = dir + tmpFile
                dataset = pydicom.dcmread(filename)
                y = dataset.data_element("PatientID").value
                covidList["PatientID"] = y
                x = dataset.data_element("PatientName").value
                covidList["PatientName"] = x
                covidList["PatientSex"] = dataset.data_element("PatientSex").value
                covidList["PatientAge"] = dataset.data_element("PatientAge").value
                covidList["StudyDate"] = dataset.data_element("StudyDate").value
                covidList["Modality"] = dataset.data_element("Modality").value
                covidList["ImageComments"] = dataset.data_element(
                    "ImageComments").value
                covidList["SeriesDescription"] = dataset.data_element(
                    "SeriesDescription").value
                covidList["BodyPartExamined"] = dataset.data_element(
                    "BodyPartExamined").value
                covidList["User"] = str(userFile)
                cl[dimg] = covidList
        return render(request, "covidct/listCovid.html", {"cl": cl})


def dcm_to_png(dcmFile, username):
    file = dcmFile
    context = {}
    userFile = username
    inputdir = 'media/covidFiles/' + str(userFile) + '/'
    outputdir = 'media/covidFiles/' + str(userFile) + '/'
    test_list = [os.path.basename(x) for x in glob.glob(inputdir + '*.dcm')]
    # print(test_list)
    for f in test_list:
        if(f == file):
            ds = pydicom.read_file(inputdir + file)
            image_2d = ds.pixel_array
            shape = ds.pixel_array.shape
            image_2d_scaled = (np.maximum(image_2d, 0) /
                               image_2d.max()) * 255.0
            image_2d_scaled = np.uint8(image_2d_scaled)

            png_file_name = outputdir + "/predicted-" + file[:-4] + ".png"

            with open(png_file_name, 'wb') as png_file:
                w = png.Writer(shape[1], shape[0], greyscale=True)
                w.write(png_file, image_2d_scaled)


def predictSpecificImage(request):
    return 0

# @login_required(login_url='/auth/login')
# def uploadToServer(request):
#     if(request.method == 'POST'):
#         fs = FileSystemStorage(location="media/covidFiles/", base_url="media/covidFiles/")
#         toup = request.FILES['filetoupload']
#         print(toup.name)
#         fdict = { 'image' : toup }
#         resp = requests.post("http://localhost:1111/fileupload", data = fdict);
#         # print(resp.status_code)
#     return render(request, 'covidct/upload_Covid.html')


context = {}
imgDict = {}


@login_required(login_url='/auth/login')
def predictCovid(request):
    userFile = request.user
    if userFile.is_superuser:
        cl = {}
        for (root, dirs, files) in os.walk('media/covidFiles'):
            for i in files:
                dir_list = os.listdir(root)
                for dimg in dir_list:
                    covidList = {}
                    tmpFile = dimg
                    if(tmpFile.endswith('.dcm')):
                        filename = root + "/" + tmpFile
                        dataset = pydicom.dcmread(filename)
                        y = dataset.data_element("PatientID").value
                        covidList["PatientID"] = y
                        x = dataset.data_element("PatientName").value
                        covidList["PatientName"] = x
                        covidList["User"] = root.split("/")[-2]
                        covidList["FileName"] = tmpFile
                        cl[dimg] = covidList
        outputdir = "media/covidFiles/" + str(userFile) + "/Predicted_Folder/"
        if (request.method == 'POST'):
            if userFile.is_superuser:
                userstmp = {}
                for (root, dirs, files) in os.walk('media/covidFiles'):
                    for i in files:
                        dir_list = os.listdir(root)
                        for dimg in dir_list:
                            userDict = {}
                            userDict["User"] = root.split("/")[-2]
                            userstmp[dimg] = userDict
            fs = FileSystemStorage(
                location=outputdir, base_url=outputdir)
            img = request.FILES['doc1']
            ims = fs.save(img.name, img)
            imgUrl = fs.url(ims)
            predicted_img = get_display_image(imgUrl)
            data = im.fromarray(predicted_img)
            rr = random.randint(0, 99)
            predicted_Image_name = 'predicted' + str(rr) + '.png'
            imgDict["predicted_Image_name"] = predicted_Image_name
            data.save(outputdir + predicted_Image_name)
            os.remove(outputdir + ims)
            MainUsersList = []
            for i in userstmp.values():

kmit-radiology-main-3/covid/templates/covidct/Covid_Home.html
{% extends 'base.html' %}
<div></div>
{% load static from staticfiles %} {% block content1 %}

<div class="container-fluid">
    <div class="parallax-covid">
        <div class="mainTitle">
            <h1>Covid - CT</h1>
        </div>
        <!-- <div class="images">
            <img src="{% static 'radioEditing.png' %}" />
        </div> -->
    </div>

    <div class="container smallContent">
        <div class="row">
            <div class="col">
                <h1 style="color: white"><u>About</u></h1>
                <div class="paragraph">
                    <p>
                        Coronavirus disease (COVID-19) is an infectious disease
                        caused by a newly discovered coronavirus. Most people
                        who fall sick with COVID-19 will experience mild to
                        moderate symptoms and recover without special treatment.
                    </p>
                    <p>
                        The virus that causes COVID-19 is mainly transmitted
                        through droplets generated when an infected person
                        coughs, sneezes, or exhales. These droplets are too
                        heavy to hang in the air, and quickly fall on floors or
                        surfaces. You can be infected by breathing in the virus
                        if you are within close proximity of someone who has
                        COVID-19, or by touching a contaminated surface and then
                        your eyes, nose or mouth.
                    </p>
                    <p>
                        By using our sophisticated AI the doctors will be able
                        to quickly predict whether a person is exposed to COVID
                        or not
                    </p>
                </div>
            </div>
            <div class="col">
                <img
                    style="float: right"
                    src="{% static 'images/covidImages/scan3.png' %}"
                    height="500px"
                    width="700px"
                />
            </div>
        </div>
    </div>
    {% if user.is_authenticated %} {% if user.is_superuser %}
    <div class="container uploading">
        <a href="{% url 'covid:upload_covid' %}"
            ><button type="button" class="btn btn-info">
                Upload and Annotate Covid - CT
            </button></a
        >
    </div>
    <div class="container uploading">
        <a href="{% url 'covid:predict_covid' %}"
            ><button type="button" class="btn btn-info">
                Predict Covid
            </button></a
        >
    </div>
    {% endif %}
    <div class="container uploading">
        <a href="{% url 'covid:list_covid' %}"
            ><button type="button" class="btn btn-info">
                Covid - CT Images on Server
            </button></a
        >
    </div>
    {% endif %}
</div>
<div>
    <footer class="text-center text-white">
        <div>
            <footer class="text-center text-white">
                <div class="container p-4">
                    <section class="mb-4">
                        <!-- Google -->
                        <a
                            class="btn btn-outline-light btn-floating m-1"
                            href="https://kmit.in/"
                            role="button"
                            ><i class="bi bi-google"></i
                        ></a>

                        <!-- Linkedin -->
                        <a
                            class="btn btn-outline-light btn-floating m-1"
                            href="#!"
                            role="button"
                            ><i class="bi bi-linkedin"></i
                        ></a>
                    </section>
                    <section class="mb-4">
                        <p>
                            This website is currently under experimental phase.
                        </p>
                        <p>
                            Please contact us if any further assistance is
                            required.
                        </p>
                    </section>
                    <!-- Section: Text -->
                </div>
                <!-- Grid container -->

                <!-- Copyright -->
                <!-- <div class="row" style="width: 100%">
					<div
						class="col text-center p-3"
						style="background-color: rgba(0, 0, 0, 0.2)"
					>
						Developed by Nishchal Singi And Team
					</div> -->
                <div
                    class="col text-center p-3"
                    style="background-color: rgba(0, 0, 0, 0.2)"
                >
                    © 2021 Copyright: KMIT
                </div>
                <!-- </div> -->

                <!-- Copyright -->
            </footer>
            <!-- Footer -->
        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->
</div>

{% endblock %}

kmit-radiology-main-3/covid/templates/covidct/listCovid.html
<!-- <!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>List</title>
        <style>
            table,
            th,
            td {
                border: 1px solid white;
            }
        </style>
    </head>
    <body style="background-color: black; color: white"> -->
{% extends 'base.html' %}
<div></div>
{% load static from staticfiles %} {% block content1 %}
<div class="container-fluid">
	<h1 style="color: white">List of Patient Images available on Server</h1>
	<br />
	<div class="table-responsive">
		<table class="table table-dark">
			<tr>
				<th>PatientID</th>
				<th>PatientName</th>
				<th>PatientSex</th>
				<th>PatientAge</th>
				<th>StudyDate</th>
				<th>Modality</th>
				<th>ImageComments</th>
				<th>SeriesDescription</th>
				<th>BodyPartExamined</th>
				<th>Posted By</th>
				<th>Predict Image</th>
			</tr>

			{% for tmp in cl.values %}
			<tr style="text-align: left">
				{% for x in tmp.values %}
				<td>{{x}}</td>
				{% endfor %} {% if request.user.is_superuser %}
				<td>
					<a href="{% url 'covid:predict_covid' %}"
						><button
							name="Predict"
							type="button"
							class="btn btn-outline-warning"
						>
							Click to Predict
						</button></a
					>
				</td>
				{% endif %}
			</tr>
			{% endfor %}
		</table>
	</div>
</div>
{% endblock %}

kmit-radiology-main-3/covid/templates/covidct/predict_Covid.html
{% extends 'base.html' %}
<div></div>
{% load static from staticfiles %} {% block content1 %}
<div>
	<div class="container center">
		<h1 style="color: white">Predict Covid - CT</h1>
		<br />
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<div class="row">
				<div class="col">
					<div class="row d-flex">
						<div class="col-auto">
							<h5 style="color: white">Upload Covid CT image</h5>
						</div>
						<div class="col-md-5 col-12">
							<input
								class="form-control form-control-sm"
								type="file"
								id="formFile"
								name="doc1"
								required
								style="background-color: black; color: white"
							/>
						</div>
						<!-- <br />
                        <br />
                        <center>
                            <h3 style="color: white">OR</h3>
                        </center>
                        <br />
                        <br />
                        <div class="col-auto">
                            <h5 style="color: white">Upload Covid CT image</h5>
                        </div>
                        <div class="col-md-5 col-12">
                            <input
                                type="text"
                                class="form-control"
                                id="inputFile"
                                name="inputDoc1"
                                placeholder="Type name of file from beside table"
                                style="background-color: black; color: white"
                            />
                        </div> -->
					</div>
				</div>
			</div>
			<br />
			<div class="col-auto">
				<button type="submit" class="btn btn-outline-warning">
					Submit
				</button>
			</div>
			<br />
			<h5 style="color: white">* upload png/jpg/jpeg images</h5>
		</form>
		<br />
		<br />
		{% if isSent %}
		<h3 style="color: white">
			The Predicted Image has been sent to {{ toSend }} user !!
		</h3>
		<br />
		{% endif %} {% if url %}
		<center>
			<a
				href="/media/covidFiles/{{ currUser }}/Predicted_Folder/{{ url }}"
				style="cursor: pointer"
			>
				<img
					src="/media/covidFiles/{{ currUser }}/Predicted_Folder/{{ url }}"
					width="1200px"
					height="800px"
				/>
			</a>
			<br />
			<br />

			<button
				type="button"
				class="btn btn-outline-info"
				data-bs-toggle="modal"
				data-bs-target="#exampleModal"
			>
				Send Predicted Image to user
			</button>

			<div
				class="modal fade"
				id="exampleModal"
				tabindex="-1"
				aria-labelledby="exampleModalLabel"
				aria-hidden="true"
			>
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<h5 class="modal-title" id="exampleModalLabel">
								Send Predicted Image to user
							</h5>
							<button
								type="button"
								class="btn-close"
								data-bs-dismiss="modal"
								aria-label="Close"
							></button>
						</div>
						<form
							class="form-check form-switch"
							method="POST"
							action="/covid/sent/"
						>
							{% csrf_token %}
							<div></div>

							<div class="modal-body">
								<ul style="list-style-type: none">
									{% for users in MainUsersList%}
									<li>
										<input
											name="checkedUser"
											class="form-check-input"
											type="checkbox"
											value="{{ users }}"
										/>
										<h4>{{ users }}</h4>
									</li>
									{% endfor %}
								</ul>
							</div>

							<div class="modal-footer">
								<button
									type="button"
									class="btn btn-secondary"
									data-bs-dismiss="modal"
								>
									Close
								</button>
								<button type="submit" class="btn btn-primary">
									Send
								</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</center>
		{% endif %}
	</div>
</div>
{% endblock %}

kmit-radiology-main-3/covid/templates/covidct/showPredicted.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        {% if url %}
        <div
            class="container center"
            style="
                margin-top: 50px;
                padding: 25px;
                background-color: #0a3d62;
                border-radius: 25px;
            "
        >
            <img src="/media/covidFiles/{{ url }}" />
            <a href="/media/covidFiles/{{ url }}"
                ><h1 style="color: white">/media/covidFiles/{{ url }}</h1></a
            >
        </div>
        {% endif %}
    </body>
</html>