kmit-radiology-main-3/kmit/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url,include
from django.urls import path
from django.urls import re_path
from django.views.static import serve

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.Home,  name="Home"),
    path("DICOM-viewer", views.Viewer, name="Viewer"),
    path('Mammography/', include('mammo.urls')), # mammo => folder name
    path('auth/', include('auths.urls')),
    path('covid/', include('covid.urls')),
]

urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

kmit-radiology-main-3/mammo/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'mammo'

urlpatterns = [
    url(r'^$', views.MammoHome, name="mammo_home"),
    url(r'^upload-mammo/$', views.uploadMammo, name="upload_Mammo"),
    url(r'^predictMammo/$', views.predictMammo, name="predictMammo")
]

kmit-radiology-main-3/mammo/models.py
from django.db import models


class Mammography(models.Model):
    title = models.CharField(max_length = 25)
    date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='Mammogram/', null=True, blank=True)

    def __str__(self):
        return self.title

kmit-radiology-main-3/mammo/forms.py
from django import forms
from .models import Mammography

class MammographyForm(forms.ModelForm):
    class Meta:
        model = Mammography
        fields = ('title', 'image')

kmit-radiology-main-3/mammo/views.py
from django.shortcuts import render
from django.core.files.storage import FileSystemStorage

import cv2
import os
import pydicom
import glob
from PIL import Image
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np

# Predicting Mammograms
#from .frcnn_test_vgg import predictt
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas

def MammoHome(request):
    #print(request.user)
    return render(request, 'mammo/MammoHome.html')


filename = "lol"
context = {}


def uploadMammo(request):
    userFile = request.user
    outputdir = 'media/mammoFiles/' + str(userFile) + '/'
    isDir = os.path.isdir(outputdir)
    if (isDir == False):
        os.mkdir(outputdir)
    
    if(request.method == 'POST'):
        imgName = request.FILES['Mammo_doc']
        #print(imgName.name)
        fs = FileSystemStorage(location=outputdir, base_url=outputdir)
        x = fs.save(imgName.name, imgName)
        filename = Convert_To_PNG(x, userFile)
        # os.remove(outputdir + x)
        context['url'] = fs.url(filename)
        #print(context['url'])
        return render(request, 'mammo/upload_Mammo.html', {'stored' : True})
    return render(request, 'mammo/upload_Mammo.html')

# def uploadMammo(request):
#     outputdir = 'media/'
#     if (request.method == 'POST'):
#         uploaded_file = request.FILES['document']
#         upName = uploaded_file.name
#         if(upName.lower().endswith('.dcm')):
#             fs = FileSystemStorage()
#             x = fs.save(uploaded_file.name, uploaded_file)
#             filename = Convert_To_PNG(x)
#             os.remove(outputdir + x)
#             context['url'] = fs.url(filename)
#             # print(context['url'])
#         else:
#             fs = FileSystemStorage()
#             filename = fs.save(uploaded_file.name, uploaded_file)
#             context['url'] = fs.url(filename)
#             # print(outputdir + x)
#     return render(request, 'mammo/uploadMammo.html', context)


def Convert_To_PNG(dcmFile, username):
    file = dcmFile
    context = {}
    userFile = username
    inputdir = 'media/mammoFiles/' + str(userFile) + '/'
    outputdir = 'media/mammoFiles/' + str(userFile) + '/'
    test_list = [os.path.basename(x) for x in glob.glob(inputdir + '*.dcm')]
    # print(test_list)
    for f in test_list:
        if(f == file):
            ds = pydicom.read_file(inputdir + f)
            img = ds.pixel_array
            cv2.imwrite(outputdir + f.replace('.dcm', '.png'), img)
    out_list = [os.path.basename(x) for x in glob.glob(inputdir + '*.png')]
    for name in out_list:
        if(name[:-4] == file[:-4]):
            return name

# @login_required(login_url='/auth/login')
def predictMammo(request):
    outputdir = 'media/mammoFiles/'
    if (request.method == 'POST'):
        fs = FileSystemStorage(location="media/mammoFiles/", base_url="media/mammoFiles/")
        img = request.FILES['mammoDoc']
        ims = fs.save(img.name, img)
        imgUrl = fs.url(ims)
        #print(imgUrl)
        inp = np.array(Image.open(img))
        #print(imgUrl.split('/')[-1])
        # pred = predictt(inp, imgUrl.split("/")[-1])
        # print(pred.shape)
    return render(request, 'mammo/predictMammo.html')

kmit-radiology-main-3/mammo/templates/mammo/MammoHome.html
{% extends 'base.html' %}
<div></div>
{% load static from staticfiles %} {% block content1 %}

<div class="container-fluid">
    <div class="parallax-mammo">
        <div class="mainTitle">
            <h1>Mammography</h1>
        </div>
        <!-- <div class="images">
            <img src="{% static 'radioEditing.png' %}" />
        </div> -->
    </div>

    <div class="container smallContent">
        <div class="row">
            <div class="col">
                <h1 style="color: white"><u>About</u></h1>
                <div class="paragraph">
                    <p>
                        A mammogram is an x-ray picture of the breast. It can be
                        used to check for breast cancer in women who have no
                        signs or symptoms of the disease. It can also be used if
                        you have a lump or other sign of breast cancer.The goal
                        of mammography is the early detection of breast cancer,
                        typically through detection of characteristic masses or
                        microcalcifications. Mammograms can be used to check for
                        breast cancer in women who have no signs or symptoms of
                        the disease. This type of mammogram is called a
                        screening mammogram. Screening mammograms usually
                        involve two or more x-ray pictures, or images, of each
                        breast. The x-ray images often make it possible to
                        detect tumors that cannot be felt. Screening mammograms
                        can also find microcalcifications (tiny deposits of
                        calcium) that sometimes indicate the presence of breast
                        cancer.
                    </p>
                    <p>
                        Mammograms can also be used to check for breast cancer
                        after a lump or other sign or symptom of the disease has
                        been found. This type of mammogram is called a
                        diagnostic mammogram. Besides a lump, signs of breast
                        cancer can include breast pain, thickening of the skin
                        of the breast, nipple discharge, or a change in breast
                        size or shape; however, these signs may also be signs of
                        benign conditions. A diagnostic mammogram can also be
                        used to evaluate changes found during a screening
                        mammogram or to view breast tissue when it is difficult
                        to obtain a screening mammogram because of special
                        circumstances, such as the presence of breast implants.
                        Early detection of breast cancer with screening
                        mammography means that treatment can be started earlier
                        in the course of the disease, possibly before it has
                        spread. Results from randomized clinical trials and
                        other studies show that screening mammography can help
                        reduce the number of deaths from breast cancer among
                        women ages 40 to 74, especially for those over age 50.
                    </p>
                </div>
            </div>
            <div class="col">
                <img
                    style="float: right"
                    src="{% static 'm2.png' %}"
                    height="500px"
                    width="700px"
                />
            </div>
        </div>
    </div>
    {% if user.is_authenticated %}
    <div class="container uploading">
        <a href="{% url 'mammo:upload_Mammo' %}"
            ><button type="button" class="btn btn-info">
                Upload Mammogram
            </button></a
        >
    </div>

    <!-- <div class="container uploading">
		<a href="{% url 'mammo:predictMammo' %}"
			><button type="button" class="btn btn-info">
				Predict Mammogram
			</button></a
		>
	</div> -->
    {% endif %}
</div>
<div>
    <footer class="text-center text-white">
        <div>
            <footer class="text-center text-white">
                <div class="container p-4">
                    <section class="mb-4">
                        <!-- Google -->
                        <a
                            class="btn btn-outline-light btn-floating m-1"
                            href="https://kmit.in/"
                            role="button"
                            ><i class="bi bi-google"></i
                        ></a>

                        <!-- Linkedin -->
                        <a
                            class="btn btn-outline-light btn-floating m-1"
                            href="#!"
                            role="button"
                            ><i class="bi bi-linkedin"></i
                        ></a>
                    </section>
                    <section class="mb-4">
                        <p>
                            This website is currently under experimental phase.
                        </p>
                        <p>
                            Please contact us if any further assistance is
                            required.
                        </p>
                    </section>
                    <!-- Section: Text -->
                </div>
                <!-- Grid container -->

                <!-- Copyright -->
                <!-- <div class="row" style="width: 100%">
					<div
						class="col text-center p-3"
						style="background-color: rgba(0, 0, 0, 0.2)"
					>
						Developed by Nishchal Singi And Team
					</div> -->
                <div
                    class="col text-center p-3"
                    style="background-color: rgba(0, 0, 0, 0.2)"
                >
                    © 2021 Copyright: KMIT
                </div>
                <!-- </div> -->

                <!-- Copyright -->
            </footer>
            <!-- Footer -->
        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->
</div>

{% endblock %}

kmit-radiology-main-3/mammo/templates/mammo/predictMammo.html
{% extends 'base.html' %}
<div></div>
{% load static from staticfiles %} {% block content1 %}
<div>
	<div class="container center">
		<h1 style="color: white">Predict Mammogram</h1>
		<br />
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<div class="row">
				<div class="col">
					<div class="row d-flex">
						<div class="col-auto">
							<h5 style="color: white">
								Upload a Mammogram image
							</h5>
						</div>
						<div class="col-md-5 col-12">
							<input
								class="form-control form-control-sm"
								type="file"
								id="formFile"
								name="mammoDoc"
								required
								style="background-color: black; color: white"
							/>
						</div>
					</div>
				</div>
			</div>
			<br />
			<div class="col-auto">
				<button type="submit" class="btn btn-outline-warning">
					Submit
				</button>
			</div>
			<br />
			<h5 style="color: white">* upload png/jpg/jpeg images</h5>
		</form>
		<br />
		<br />
		{% if url %}
		<center>
			<a href="/media/covidFiles/{{ url }}" style="cursor: pointer">
				<img
					src="/media/covidFiles/{{ url }}"
					width="1200px"
					height="800px"
				/>
			</a>
			<br />
			<br />

			<button
				class="btn btn-outline-danger"
				onclick="handleUploadToServer(`{{ url }}`)"
			>
				Upload Image to server
			</button>
			<script>
				function handleUploadToServer(url) {
					// console.log(url);
					setTimeout(() => {
						alert(
							`Image uploaded to server\nImage is saved as - ` +
								url
						);
					});
				}
			</script>
		</center>
		{% endif %}
	</div>
</div>
{% endblock %}

kmit-radiology-main-3/mammo/templates/mammo/predictedMammo.html
{% extends 'base.html' %}
<div></div>
{% load static from staticfiles %} {% block content1 %}
<div>
    <div
        class="container center"
        style="
            margin-top: 50px;
            padding: 25px;
            background-color: #0a3d62;
            border-radius: 25px;
        "
    >
        <script src="{% static 'js/annotations/openseadragon-annotorious.min.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/@recogito/annotorious-toolbar@latest/dist/annotorious-toolbar.min.js"></script>
        <link
            rel="stylesheet"
            href="{% static 'js/annotations/annotorious.min.css' %}"
        />

        <center>
            <div class="row container center">
                <div class="col-lg-7">
                    <button
                        class="btn btn-success"
                        type="submit"
                        id="save"
                        onclick="saveAnnotations()"
                    >
                        Save Annotations
                    </button>
                    <div
                        id="show"
                        class="position-fixed bottom-0 end-0 p-3"
                        style="z-index: 5"
                    ></div>
                </div>
                <div
                    class="col-lg-3"
                    id="toolbar-container"
                    style="
                        background-color: #fa983a;
                        border-radius: 25px;
                        margin-bottom: 25px;
                        padding: 5px;
                    "
                ></div>
            </div>
            <div id="openseadragon1" style="width: 800px; height: 600px"></div>
        </center>

        <script type="text/javascript">
            var viewer = OpenSeadragon({
                id: "openseadragon1",
                navigatorPosition: "TOP_RIGHT",
                showNavigator: true,
                prefixUrl: "{% static 'js/openseadragon/images/' %}",
                tileSources: {
                    type: "image",
                    url: "{{ url }}",
                    buildPyramid: false,
                },
            });
            var anno = OpenSeadragon.Annotorious(viewer);
            Annotorious.Toolbar(
                anno,
                document.getElementById("toolbar-container")
            );
            anno.addDrawingTool();
        </script>

        <br />
        <div
            style="z-index: 10"
            class="alert alert-info alert-dismissible fade-out show position-fixed bottom-0 end-0 p-5 m-4"
            role="alert"
        >
            <strong>Save Annotations before downloading !!</strong>
            <br />
            <p id="currentDateTime" style="color: gray"></p>
            <script>
                var today = new Date();
                var date =
                    today.getDate() +
                    "-" +
                    (today.getMonth() + 1) +
                    "-" +
                    today.getFullYear();

                var time =
                    today.getHours() +
                    ":" +
                    today.getMinutes() +
                    ":" +
                    today.getSeconds();
                var dateTime = date + " " + time;
                document.getElementById(
                    "currentDateTime"
                ).innerHTML += dateTime;
            </script>

            <button
                type="button"
                class="btn-close"
                data-bs-dismiss="alert"
                aria-label="Close"
            ></button>
        </div>
        <center>
            <div class="row container center">
                <div class="col">
                    <button
                        class="btn btn-success"
                        type="submit"
                        id="download"
                        onclick="download_JSON()"
                    >
                        Download Annotations as JSON
                    </button>
                </div>
                <div class="col">
                    <button
                        class="btn btn-success"
                        type="submit"
                        id="download"
                        onclick="download_CSV()"
                    >
                        Download Annotations as CSV
                    </button>
                </div>
                <div class="col">
                    <button
                        class="btn btn-success"
                        type="submit"
                        id="download"
                        onclick="download_AnnoPic()"
                    >
                        Save Predicted Image
                    </button>
                </div>
            </div>
        </center>
    </div>
    <script src="{% static 'js/annotationsView.js' %}"></script>
</div>
{% endblock %}

kmit-radiology-main-3/mammo/templates/mammo/uploadMammo.html
{% extends 'base.html' %}
<div></div>
{% load static from staticfiles %} {% block content1 %}
<div>
    <div
        class="container center"
        style="
            background-color: #0c2461;
            padding: 25px;
            margin-top: 55px;
            border-radius: 25px;
        "
    >
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row d-flex justify-content-center">
                <div class="col-auto">
                    <h3 style="color: white">Upload a mammogram</h3>
                </div>
                <div class="col-md-5 col-12">
                    <input
                        class="form-control"
                        type="file"
                        id="formFile"
                        name="document"
                        required
                    />
                </div>
                <div class="col-auto">
                    <button type="submit" class="btn btn-success">
                        Upload
                    </button>
                </div>
                <br />
            </div>
        </form>
    </div>
    <!-- <div class="container center" style="margin-top: 50px; padding: 25px">
    {% if url %}
    <!-- <img src="{{ url }}" alt="img" />
    <center>
        <div id="openseadragon1" style="width: 800px; height: 600px"></div>
    </center>

    <script type="text/javascript">
        var viewer = OpenSeadragon({
            id: "openseadragon1",
            prefixUrl: "{% static 'openseadragon/images/' %}",
            tileSources: {
                type: "image",
                url: "{{ url }}",
                buildPyramid: false,
            },
        });
        viewer.initializeAnnotations();
    </script>
    {% endif %}
</div> -->
    {% if url %}
    <div
        class="container center"
        style="
            margin-top: 50px;
            padding: 25px;
            background-color: #0a3d62;
            border-radius: 25px;
        "
    >
        <script src="{% static 'js/annotations/openseadragon-annotorious.min.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/@recogito/annotorious-toolbar@latest/dist/annotorious-toolbar.min.js"></script>
        <link
            rel="stylesheet"
            href="{% static 'js/annotations/annotorious.min.css' %}"
        />

        <center>
            <a href="{{ url }}">{{ url }}</a>
            <div class="row">
                <div class="col">
                    <button
                        class="btn btn-success"
                        type="submit"
                        id="save"
                        onclick="saveAnnotations()"
                    >
                        Save Annotations
                    </button>
                    <div
                        id="show"
                        class="position-fixed bottom-0 end-0 p-3"
                        style="z-index: 5"
                    ></div>
                </div>
                <div
                    class="col-lg-2"
                    id="toolbar-container"
                    style="
                        background-color: #fa983a;
                        border-radius: 25px;
                        margin-bottom: 25px;
                        padding: 5px;
                    "
                ></div>
                <div class="col">
                    <form action="/Mammography/predictMammo">
                        <button
                            class="btn btn-success"
                            type="submit"
                            id="predictAnnotations"
                        >
                            Predict
                        </button>
                    </form>
                </div>
            </div>
            <div id="openseadragon1" style="width: 800px; height: 600px"></div>
        </center>

        <script type="text/javascript">
            var viewer = OpenSeadragon({
                id: "openseadragon1",
                navigatorPosition: "TOP_RIGHT",
                showNavigator: true,
                prefixUrl: "{% static 'js/openseadragon/images/' %}",
                tileSources: {
                    type: "image",
                    url: "{{ url }}",
                    buildPyramid: false,
                },
            });
            var anno = OpenSeadragon.Annotorious(viewer);
            Annotorious.Toolbar(
                anno,
                document.getElementById("toolbar-container")
            );
            anno.addDrawingTool();
        </script>

        <br />
        <div
            style="z-index: 10"
            class="
                alert alert-info alert-dismissible
                fade-out
                show
                position-fixed
                bottom-0
                end-0
                p-5
                m-4
            "
            role="alert"
        >
            <strong>Save Annotations before downloading !!</strong>
            <button
                type="button"
                class="btn-close"
                data-bs-dismiss="alert"
                aria-label="Close"
            ></button>
        </div>
        <center>
            <div class="row container center">
                <div class="col">
                    <button
                        class="btn btn-success"
                        type="submit"
                        id="download"
                        onclick="download_JSON()"
                    >
                        Download Annotations as JSON
                    </button>
                </div>
                <div class="col">
                    <button
                        class="btn btn-success"
                        type="submit"
                        id="download"
                        onclick="download_CSV()"
                    >
                        Download Annotations as CSV
                    </button>
                </div>
                <div class="col">
                    <button
                        class="btn btn-success"
                        type="submit"
                        id="download"
                        onclick="download_AnnoPic()"
                    >
                        Download Annotated Pic
                    </button>
                </div>
                <!-- <input type="file" id="loadAnnoFile" /> -->
            </div>
            <!-- <br />
            <br /> -->

            <!-- <div class="row d-flex justify-content-center">
                <div class="col-auto">
                    <h4 style="color: white">
                        Upload File to load Annotations
                    </h4>
                </div>
                <div class="col-md-5 col-12">
                    <input
                        class="form-control"
                        type="file"
                        id="loadingAnnoFile"
                        name="document"
                        required
                    />
                </div>
                <div class="col-auto">
                    <button
                        type="submit"
                        class="btn btn-success"
                        onclick="loadAnnotations(event)"
                    >
                        Load Annotations
                    </button>
                </div>
                <br />
            </div> -->
        </center>
    </div>
    <script src="{% static 'js/annotationsView.js' %}"></script>
    {% else %}
    <div
        class="container"
        style="padding: 25px; background-color: black; height: 708px"
    ></div>
    {% endif %}
</div>
{% endblock %}