kmit-radiology-main-3/auths/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'auths'

urlpatterns = [
    # url(r'^signup/', views.Signup, name="signup"),
    url(r'^login/$', views.Login, name="login"),
    url(r'^logout/$', views.Logout, name = "logout"),
]

kmit-radiology-main-3/covid/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'covid'

urlpatterns = [
    url(r'^$', views.CovidHome, name="covid_home"),
    url(r'^upload_covid/$', views.uploadCovid, name="upload_covid"),
    url(r'^predictCovid/$', views.predictCovid, name="predict_covid"),
    url(r'^showCovid/$', views.showCovid, name="show_covid"),
    url(r'^getCovitCT/$', views.getCovidList, name="list_covid"),
    url(r'^sent/$', views.sentImage, name="sent_Image")
    # url(r'^fileupload/$', views.uploadToServer, name="upload_server")
]

kmit-radiology-main-3/kmit/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url,include
from django.urls import path
from django.urls import re_path
from django.views.static import serve

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.Home,  name="Home"),
    path("DICOM-viewer", views.Viewer, name="Viewer"),
    path('Mammography/', include('mammo.urls')), # mammo => folder name
    path('auth/', include('auths.urls')),
    path('covid/', include('covid.urls')),
]

urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

kmit-radiology-main-3/mammo/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'mammo'

urlpatterns = [
    url(r'^$', views.MammoHome, name="mammo_home"),
    url(r'^upload-mammo/$', views.uploadMammo, name="upload_Mammo"),
    url(r'^predictMammo/$', views.predictMammo, name="predictMammo")
]

kmit-radiology-main-3/templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
			crossorigin="anonymous"
		/>
		<script
			src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
			integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG"
			crossorigin="anonymous"
		></script>
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
			integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc"
			crossorigin="anonymous"
		></script>
		<link
			rel="stylesheet"
			href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css"
		/>
		<script src="{% static 'js/openseadragon/openseadragon.min.js' %}"></script>

		<link rel="stylesheet" href="{% static 'baseStyles.css' %}" />
		<title>KMIT-R.AI.DIOLOGY</title>
	</head>
	<body style="background-color: black">
		<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
			<div class="container">
				<a class="navbar-brand" href="{% url 'Home' %}"
					>KMIT - R.<em style="color: red">AI</em>.DIOLOGY</a
				>
				<button
					class="navbar-toggler"
					type="button"
					data-bs-toggle="collapse"
					data-bs-target="#navbarSupportedContent"
					aria-controls="navbarSupportedContent"
					aria-expanded="false"
					aria-label="Toggle navigation"
				>
					<span class="navbar-toggler-icon"></span>
				</button>
				<div
					class="collapse navbar-collapse"
					id="navbarSupportedContent"
				>
					<ul class="navbar-nav ms-auto mb-2 mb-lg-0">
						<li class="nav-item">
							<a
								class="nav-link active"
								aria-current="page"
								href="{% url 'Home' %}"
								>Home</a
							>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">About</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">Contact</a>
						</li>
						<li>
							<div
								class="collapse navbar-collapse"
								id="navbarNavDarkDropdown"
							>
								<ul class="navbar-nav">
									<li class="nav-item dropdown">
										<a
											class="nav-link dropdown-toggle"
											href="#"
											id="navbarDarkDropdownMenuLink"
											role="button"
											data-bs-toggle="dropdown"
											aria-expanded="false"
										>
											Facilities
										</a>
										<ul
											class="
												dropdown-menu dropdown-menu-dark
											"
											aria-labelledby="navbarDarkDropdownMenuLink"
										>
											<li>
												<a
													class="dropdown-item"
													href="{% url 'covid:covid_home' %}"
													>COVID - CT</a
												>
											</li>
											<li>
												<a
													class="dropdown-item"
													href="{% url 'mammo:mammo_home' %}"
													>Mammography</a
												>
											</li>
											{% if user.is_authenticated %}
											<li>
												<a
													class="dropdown-item"
													href="{% url 'Viewer' %}"
													>DICOM Viewer</a
												>
											</li>
											{% endif %}
										</ul>
									</li>
								</ul>
							</div>
						</li>
						{% if user.is_authenticated %}
						<li class="nav-item">
							<a href="{% url 'auths:logout' %}">
								<button class="btn btn-danger" type="submit">
									Logout
								</button>
							</a>
						</li>
						{% else %}
						<li class="nav-item">
							<a href="{% url 'auths:login' %}">
								<button
									class="btn btn-outline-info"
									type="submit"
								>
									Login
								</button>
							</a>
						</li>
						{% endif %}
					</ul>
				</div>
			</div>
		</nav>
		<div class="container-fluid">{% block content1 %} {% endblock %}</div>
	</body>
</html>

kmit-radiology-main-3/templates/home.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
            crossorigin="anonymous"
        />
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
            integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
            integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc"
            crossorigin="anonymous"
        ></script>
        <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css"
        />
        <link rel="stylesheet" href="{% static 'home.css' %}" />
        <title>KMIT - R.AI.DIOLOGY</title>
    </head>
    <body>
        <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'Home' %}"
                    >KMIT - R.<em style="color: red">AI</em>.DIOLOGY</a
                >
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div
                    class="collapse navbar-collapse"
                    id="navbarSupportedContent"
                >
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a
                                class="nav-link active"
                                aria-current="page"
                                href="{% url 'Home' %}"
                                >Home</a
                            >
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#Contact">Contact</a>
                        </li>
                        <li>
                            <div
                                class="collapse navbar-collapse"
                                id="navbarNavDarkDropdown"
                            >
                                <ul class="navbar-nav">
                                    <li class="nav-item dropdown">
                                        <a
                                            class="nav-link dropdown-toggle"
                                            href="#"
                                            id="navbarDarkDropdownMenuLink"
                                            role="button"
                                            data-bs-toggle="dropdown"
                                            aria-expanded="false"
                                        >
                                            Facilities
                                        </a>
                                        <ul
                                            class="
                                                dropdown-menu dropdown-menu-dark
                                            "
                                            aria-labelledby="navbarDarkDropdownMenuLink"
                                        >
                                            <li>
                                                <a
                                                    class="dropdown-item"
                                                    href="{% url 'covid:covid_home' %}"
                                                    >COVID - CT</a
                                                >
                                            </li>
                                            <li>
                                                <a
                                                    class="dropdown-item"
                                                    href="{% url 'mammo:mammo_home' %}"
                                                    >Mammography</a
                                                >
                                            </li>
                                            {% if user.is_authenticated %}
                                            <li>
                                                <a
                                                    class="dropdown-item"
                                                    href="{% url 'Viewer' %}"
                                                    >DICOM Viewer</a
                                                >
                                            </li>
                                            {% endif %}
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a href="{% url 'auths:logout' %}">
                                <button class="btn btn-danger" type="submit">
                                    Logout
                                </button>
                            </a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a href="{% url 'auths:login' %}">
                                <button
                                    class="btn btn-outline-info"
                                    type="submit"
                                >
                                    Login
                                </button>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container-fluid">
            <div class="parallax">
                <div class="mainTitle">
                    <h1>KMIT - R.<em style="color: red">AI</em>.DIOLOGY</h1>
                </div>
                <!-- <div class="images">
                    <img src="{% static 'radioEditing.png' %}" />
                </div> -->
            </div>

            <div class="container smallContent">
                <div class="row">
                    <div class="col">
                        <h1 style="color: white" id="About"><u>About</u></h1>
                        <div class="paragraph">
                            <p>
                                Radiology is the medical discipline that uses
                                medical imaging to diagnose and treat diseases
                                within the bodies of animals and humans. A
                                variety of imaging techniques such as X-ray
                                radiography, ultrasound, computed tomography
                                (CT), nuclear medicine including positron
                                emission tomography (PET), fluoroscopy, and
                                magnetic resonance imaging (MRI) are used to
                                diagnose or treat diseases. Interventional
                                radiology is the performance of usually
                                minimally invasive medical procedures with the
                                guidance of imaging technologies such as those
                                mentioned above.
                            </p>
                            <p>
                                The modern practice of radiology involves
                                several different healthcare professions working
                                as a team. The radiologist is a medical doctor
                                who has completed the appropriate post-graduate
                                training and interprets medical images,
                                communicates these findings to other physicians
                                by means of a report or verbally, and uses
                                imaging to perform minimally invasive medical
                                procedures. The nurse is involved in the care of
                                patients before and after imaging or procedures,
                                including administration of medications,
                                monitoring of vital signs and monitoring of
                                sedated patients. The radiographer, also known
                                as a "radiologic technologist" in some countries
                                such as the United States and Canada, is a
                                specially trained healthcare professional that
                                uses sophisticated technology and positioning
                                techniques to produce medical images for the
                                radiologist to interpret. Depending on the
                                individual's training and country of practice,
                                the radiographer may specialize in one of the
                                above-mentioned imaging modalities or have
                                expanded roles in image reporting.
                            </p>
                        </div>
                    </div>
                    <div class="col">
                        <img
                            style="float: right"
                            src="{% static 'radiopic1.jpg' %}"
                            height="500px"
                            width="500px"
                        />
                    </div>
                </div>
            </div>
            <div class="container smallContent">
                <div class="row">
                    <div class="col">
                        <img
                            style="float: left"
                            src="{% static 'radiopic2.jpg' %}"
                            height="500px"
                            width="500px"
                        />
                    </div>
                    <div class="col">
                        <h1 style="color: white" id="Contact">
                            <u>Contact</u>
                        </h1>
                        <div class="paragraph">
                            <p>Dr. S. Rajasekaran: rajasekarans@kmit.in</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="parallax1"></div>
        </div>
        <div>
            <footer class="text-center text-white">
                <div class="container p-4">
                    <section class="mb-4">
                        <!-- Google -->
                        <a
                            class="btn btn-outline-light btn-floating m-1"
                            href="https://kmit.in/"
                            role="button"
                            ><i class="bi bi-google"></i
                        ></a>

                        <!-- Linkedin -->
                        <a
                            class="btn btn-outline-light btn-floating m-1"
                            href="#!"
                            role="button"
                            ><i class="bi bi-linkedin"></i
                        ></a>
                    </section>
                    <section class="mb-4">
                        <p>
                            This website is currently under experimental phase.
                        </p>
                        <p>
                            Please contact us if any further assistance is
                            required.
                        </p>
                    </section>
                    <!-- Section: Text -->
                </div>
                <!-- Grid container -->

                <!-- Copyright -->
                <!-- <div class="row" style="width: 100%">
					<div
						class="col text-center p-3"
						style="background-color: rgba(0, 0, 0, 0.2)"
					>
						Developed by Nishchal Singi And Team
					</div> -->
                <div
                    class="col text-center p-3"
                    style="background-color: rgba(0, 0, 0, 0.2)"
                >
                    © 2021 Copyright: KMIT
                </div>
                <!-- </div> -->

                <!-- Copyright -->
            </footer>
            <!-- Footer -->
        </div>
    </body>
</html>